# Generated by Django 4.2.7 on 2024-02-16 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DateofBirth',
            field=models.DateField(default=datetime.date(2000, 1, 1), null=True),
        ),
    ]
